App.Lead = DS.Model.extend
  user:           DS.belongsTo('App.User', { inverse: 'leadsAsCreator' })
  campaignId:     DS.belongsTo('App.Campaign')
  assignedTo:     DS.belongsTo('App.User', { inverse: 'leadsAsAssignee' })
  firstName:      DS.attr('string')
  lastName:       DS.attr('string')
  salutation:     DS.attr('string')
  company:        DS.attr('string')
  source:         DS.attr('string')
  referredBy:     DS.attr('string')
  email:          DS.attr('string')
  blog:           DS.attr('string')
  linkedin:       DS.attr('string')
  facebook:       DS.attr('string')
  twitter:        DS.attr('string')
  skype:          DS.attr('string')
  rating:         DS.attr('number')
  doNotCall:      DS.attr('boolean')
  backgroundInfo: DS.attr('string')
  createdAt:      DS.attr('string')
  updatedAt:      DS.attr('string')
  street:         DS.attr('string')
  city:           DS.attr('string')
  region:         DS.attr('string')
  postal_code:    DS.attr('string')
  country:        DS.attr('string')
  phone:          DS.attr('string')
  mobile:         DS.attr('string')

  displayName: (->
    [@get('firstName'), @get('lastName')].compact().join(' ')
  ).property('firstName', 'lastName')
