defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: postgres
  host: 127.0.0.1

development:
  <<: *defaults
  database: salesflip_development

test:
  <<: *defaults
  database: salesflip_test

staging:
  <<: *defaults
  database: salesflip_staging

production:
  <<: *defaults
  database: salesflip_production
