#= require ./store
#= require_tree ./models
#= require ./controllers/modal
#= require_tree ./controllers
#= require ./views/modal
#= require_tree ./views
#= require_tree ./helpers
#= require_tree ./templates
#= require_tree ./routes
#= require ./router
#= require_self
